### PR TITLE
Industry Contact Form

### PR DESCRIPTION
**Pull request by dianzrong**
#8: This PR implements the industry contact form

TODO:

- [x] Make the font and colour more cohesive with the rest of the website
- [x] Make the buttons in the Industries Grid scroll down to the Contact Form
     - [x] Auto populate the last form field with the relevant industry

### CODE REVIEW

**Comment by dianzrong** [comment]
@abrichr I merged the 2 PRs

**Comment by abrichr** [comment]
Thanks @dianzrong !!

image

Please implement the following changes:

- "OpenAdapt.AI" -> "Join the waitlist"
- "Fill out your email and we'll let you know when you can access your spot for OpenAdapt Alpha" -> "Submit this form to get on the waitlist"
- "How did you hear about us? [Optional]" -> (remove)
- "How can OpenAdapt help you? [Optional]" -> "How can we help?"
- "Submit" -> center
- "Register for updates (we promise not to spam)" -> center

🙏

**Comment by abrichr** [comment]
For reference, the original design in the issue:

image

What we have now:

image

Let's use the "Fill out this form" and "How can OpenAdapt help you" text

Also please adjust the vertical margin/padding to be symmetrical as in the design 🙏

**Comment by dianzrong** [comment]
@abrichr Could I get some clarification on what is supposed be symmetrical?

**Comment by abrichr** [comment]
TODO:
- fix "get started" scroll to industries grid
- modify "get started" to "learn how"
- change input to textarea
- make sure email / message are being stored separately
- asynchronous form submission
- hide form / replace with "Successfully submitted. We will reach out when your spot is available."
- fix: "getting started for developers" disappears on form submit
- deploy to development instance (optional)

**Pull request merged**
